/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MyTripsRouteImport } from './routes/my-trips'
import { Route as PostRideRouteImport } from './routes/post-ride'
import { Route as RidesRouteImport } from './routes/rides'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as RidesRideIdRouteImport } from './routes/rides.$rideId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsRoute = MyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRideRoute = PostRideRouteImport.update({
  id: '/post-ride',
  path: '/post-ride',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRoute = RidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRideIdRoute = RidesRideIdRouteImport.update({
  id: '/$rideId',
  path: '/$rideId',
  getParentRoute: () => RidesRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-trips': typeof MyTripsRoute
  '/post-ride': typeof PostRideRoute
  '/rides': typeof RidesRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-trips': typeof MyTripsRoute
  '/post-ride': typeof PostRideRoute
  '/rides': typeof RidesRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/my-trips': typeof MyTripsRoute
  '/post-ride': typeof PostRideRoute
  '/rides': typeof RidesRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/my-trips'
    | '/post-ride'
    | '/rides'
    | '/checkout/return'
    | '/rides/$rideId'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/my-trips'
    | '/post-ride'
    | '/rides'
    | '/checkout/return'
    | '/rides/$rideId'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/my-trips'
    | '/post-ride'
    | '/rides'
    | '/checkout/return'
    | '/rides/$rideId'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MyTripsRoute: typeof MyTripsRoute
  PostRideRoute: typeof PostRideRoute
  RidesRoute: typeof RidesRouteWithChildren
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips': {
      id: '/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof MyTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-ride': {
      id: '/post-ride'
      path: '/post-ride'
      fullPath: '/post-ride'
      preLoaderRoute: typeof PostRideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides': {
      id: '/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/$rideId': {
      id: '/rides/$rideId'
      path: '/$rideId'
      fullPath: '/rides/$rideId'
      preLoaderRoute: typeof RidesRideIdRouteImport
      parentRoute: typeof RidesRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RidesRouteChildren {
  RidesRideIdRoute: typeof RidesRideIdRoute
}

const RidesRouteChildren: RidesRouteChildren = {
  RidesRideIdRoute: RidesRideIdRoute,
}

const RidesRouteWithChildren = RidesRoute._addFileChildren(RidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MyTripsRoute: MyTripsRoute,
  PostRideRoute: PostRideRoute,
  RidesRoute: RidesRouteWithChildren,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
