/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeDriverRouteImport } from './routes/become-driver'
import { Route as MyTripsRouteImport } from './routes/my-trips'
import { Route as PostRideRouteImport } from './routes/post-ride'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as RidesIndexRouteImport } from './routes/rides.index'
import { Route as RidesRideIdRouteImport } from './routes/rides.$rideId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeDriverRoute = BecomeDriverRouteImport.update({
  id: '/become-driver',
  path: '/become-driver',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTripsRoute = MyTripsRouteImport.update({
  id: '/my-trips',
  path: '/my-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const PostRideRoute = PostRideRouteImport.update({
  id: '/post-ride',
  path: '/post-ride',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesIndexRoute = RidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRideIdRoute = RidesRideIdRouteImport.update({
  id: '/rides/$rideId',
  path: '/rides/$rideId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-driver': typeof BecomeDriverRoute
  '/my-trips': typeof MyTripsRoute
  '/post-ride': typeof PostRideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/rides/': typeof RidesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-driver': typeof BecomeDriverRoute
  '/my-trips': typeof MyTripsRoute
  '/post-ride': typeof PostRideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/rides': typeof RidesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-driver': typeof BecomeDriverRoute
  '/my-trips': typeof MyTripsRoute
  '/post-ride': typeof PostRideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/rides/': typeof RidesIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/become-driver'
    | '/my-trips'
    | '/post-ride'
    | '/sitemap.xml'
    | '/admin/drivers'
    | '/checkout/return'
    | '/rides/$rideId'
    | '/rides/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/become-driver'
    | '/my-trips'
    | '/post-ride'
    | '/sitemap.xml'
    | '/admin/drivers'
    | '/checkout/return'
    | '/rides/$rideId'
    | '/rides'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/become-driver'
    | '/my-trips'
    | '/post-ride'
    | '/sitemap.xml'
    | '/admin/drivers'
    | '/checkout/return'
    | '/rides/$rideId'
    | '/rides/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BecomeDriverRoute: typeof BecomeDriverRoute
  MyTripsRoute: typeof MyTripsRoute
  PostRideRoute: typeof PostRideRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminDriversRoute: typeof AdminDriversRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  RidesRideIdRoute: typeof RidesRideIdRoute
  RidesIndexRoute: typeof RidesIndexRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-driver': {
      id: '/become-driver'
      path: '/become-driver'
      fullPath: '/become-driver'
      preLoaderRoute: typeof BecomeDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-trips': {
      id: '/my-trips'
      path: '/my-trips'
      fullPath: '/my-trips'
      preLoaderRoute: typeof MyTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-ride': {
      id: '/post-ride'
      path: '/post-ride'
      fullPath: '/post-ride'
      preLoaderRoute: typeof PostRideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/': {
      id: '/rides/'
      path: '/rides'
      fullPath: '/rides/'
      preLoaderRoute: typeof RidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/$rideId': {
      id: '/rides/$rideId'
      path: '/rides/$rideId'
      fullPath: '/rides/$rideId'
      preLoaderRoute: typeof RidesRideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BecomeDriverRoute: BecomeDriverRoute,
  MyTripsRoute: MyTripsRoute,
  PostRideRoute: PostRideRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminDriversRoute: AdminDriversRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  RidesRideIdRoute: RidesRideIdRoute,
  RidesIndexRoute: RidesIndexRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
